version: "3.9"
services:
  api:
    build:
      context: ./api
      args:
        - target=dev
    volumes:
      - ./api:/app
    environment:
      TODO_ENV: dev
      PORT: 8001
    ports:
      - "8001:8001"

