version: "3.9"
services:
  api:
    build:
      context: ./api
      args:
        - target=dev
    volumes:
      - ./api:/app
    environment:
      TODO_ENV: dev
      PORT: 8001
      TODO_DB_HOST: db
      TODO_DB_PORT: 3306
      TODO_DB_USER: todo
      TODO_DB_PASSWORD: todo
      TODO_DB_NAME: todo
      TODO_REDIS_HOST: redis
      TODO_REDIS_PORT: 6379
    ports:
      - "8001:8001"
  db:
    image: mysql:8.0.29
    platform: linux/amd64
    container_name: todo-db
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: todo
      MYSQL_USER: todo
      MYSQL_PASSWORD: todo
    volumes:
      - ./db/initdb.d:/docker-entrypoint-initdb.d
      - todo-db-data:/var/lib/mysql
      - ./db/mysql/conf.d:/etc/mysql/conf.d:cached
    ports:
      - "33306:3306"
      - "33060:33060"
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "36379:6379"
volumes:
  todo-db-data:
  todo-redis-data:
