version: '3'
env:
  DOCKER_TAG: latest

tasks:
  default:
    deps:
      - test
      - up
    cmds:
      - task: logs

  build:
    desc: Build docker image to deploy
    cmds:
      - docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} --target deploy api/
    silent: true

  build-local:
    desc: Build docker image to development
    cmds:
      - docker compose build --no-cache
    silent: true

  test:
    desc: Run Test
    deps:
      - { "task": up, "vars": {"CLI_ARGS": "db redis"}}
        # vars:
        #   CLI_ARGS: db redis
    dir: api/
    env:
      PORT: 3333
      TODO_DB_HOST: 127.0.0.1
      TODO_DB_PORT: 33306
      TODO_DB_NAME: todo_test
      TODO_DB_USER: todo_test
      TODO_DB_PASSWORD: todo_test
      TODO_REDIS_HOST: 127.0.0.1
      TODO_REDIS_PORT: 36379
    cmds:
      - go test -race -shuffle=on ./... --coverprofile=coverage.out {{ .CLI_ARGS }}

  up:
    desc: up with hot relaod
    cmds:
      - docker compose up --build -d {{ .CLI_ARGS }}
    silent: true

  down:
    desc: down
    cmds:
      - docker compose down

  logs:
    desc: logs
    cmds:
      - docker compose logs --tail=100 -f {{ .CLI_ARGS }}

  mod:
    dir: api/
    cmds:
      - go mod tidy
  ps:
    desc: ps 
    cmds:
      - docker compose ps

  migrate:
    desc: Execute migration for local DB
    cmds:
      - |
        mysqldef -u todo -p todo -h 127.0.0.1 -P 33306 todo \
        < ./api/_tools/mysql/schema.sql
      - |
        mysqldef -u todo_test -p todo_test -h 127.0.0.1 -P 33306 todo_test \
        < ./api/_tools/mysql/schema.sql

  dry-migrate:
    desc: Execute DB migration as a dry run for local DB
    cmds:
      - |
        mysqldef -u todo -p todo -h 127.0.0.1 -P 33306 todo --dry-run \
        < ./api/_tools/mysql/schema.sql
      - |
        mysqldef -u todo_test -p todo_test -h 127.0.0.1 -P 33306 todo_test --dry-run \
        < ./api/_tools/mysql/schema.sql

  generate:
    desc: Generate code by go generate
    dir: api/
    cmds:
      - go generate ./...