version: '3'
env:
  DOCKER_TAG: latest

tasks:
  build:
    desc: Build docker image to deploy
    cmds:
      - docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} --target deploy api/
    silent: true

  build-local:
    desc: Build docker image to development
    cmds:
      - docker compose build --no-cache
    silent: true

  test:
    desc: Run Test
    deps:
      - build-local
    dir: api
    cmds:
      - go test -race -shuffle=on -v ./...

  up:
    desc: up with hot relaod
    cmds:
      - docker compose up -d
      - task: logs
    silent: true

  down:
    desc: down
    cmds:
      - docker compose down

  logs:
    desc: logs
    cmds:
      - docker compose logs --tail=100 -f

  ps:
    desc: ps 
    cmds:
      - docker compose ps
