version: '3'
env:
  DOCKER_TAG: latest

tasks:
  default:
    deps:
      - test
      - up
    cmds:
      - task: logs

  build:
    desc: Build docker image to deploy
    cmds:
      - docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} --target deploy api/
    silent: true

  build-local:
    desc: Build docker image to development
    cmds:
      - docker compose build --no-cache
    silent: true

  test:
    desc: Run Test
    dir: api/
    env:
      TODO_DB_PORT: 33306
    cmds:
      - echo $TODO_DB_PORT
      - go test -race -shuffle=on ./... --coverprofile=coverage.out {{ .CLI_ARGS }}

  up:
    desc: up with hot relaod
    deps:
      - build-local
    cmds:
      - docker compose up -d {{ .CLI_ARGS }}
    silent: true

  down:
    desc: down
    cmds:
      - docker compose down

  logs:
    desc: logs
    cmds:
      - docker compose logs --tail=100 -f {{ .CLI_ARGS }}

  mod:
    dir: api/
    cmds:
      - go mod tidy
  ps:
    desc: ps 
    cmds:
      - docker compose ps

  migrate:
    desc: Execute migration for local DB
    cmds:
      - |
        mysqldef -u todo -p todo -h 127.0.0.1 -P 33306 todo \
        < ./api/_tools/mysql/schema.sql

  dry-migrate:
    desc: Execute DB migration as a dry run for local DB
    cmds:
      - |
        mysqldef -u todo -p todo -h 127.0.0.1 -P 33306 todo --dry-run \
        < ./api/_tools/mysql/schema.sql

  generate:
    desc: Generate code by go generate
    dir: api/
    cmds:
      - go generate ./...