version: '3'
env:
  DOCKER_TAG: latest

tasks:
  build:
    desc: Build docker image to deploy
    cmds:
      - docker build -t ${DOCKER_IMAGE_NAME}:${DOCKER_TAG} --target deploy api/
    silent: true

  build-local:
    desc: Build docker image to development
    cmds:
      - docker compose build --no-cache
    silent: true

  test:
    desc: Run Test
    dir: api
    cmds:
      - go test -race -shuffle=on -v ./...

  up:
    desc: up with hot relaod
    cmds:
      - docker compose up -d
    silent: true

  down:
    desc: down
    cmds:
      - docker compose down

  logs:
    desc: logs
    cmds:
      - docker compose logs --tail=100 -f

  ps:
    desc: ps 
    cmds:
      - docker compose ps

  migrate:
    desc: Migrate local DB
    deps:
      - up
    cmds:
      - |
        mysqldef -u todo -p todo -h 127.0.0.1 -P 33306 todo \
        < ./api/_tools/mysql/schema.sql
